TrainingApp/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data.Entity;
using System.Security.Claims;
using TrainingApp.Data;
using TrainingApp.Models;
using TrainingApp.Service;

namespace TrainingApp.Controllers
{
    [ReturnToHome]
    public class DashboardController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly IWorkoutPlanService _workoutPlanService; // Assuming you have a service to handle workout plans
        private readonly AppDbContext _dbContext;
        public DashboardController(UserManager<AppUser> userManager, IWorkoutPlanService workoutPlanService, AppDbContext dbContext)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _workoutPlanService = workoutPlanService;
        }

        public async Task<IActionResult> Index()
        {
                var user = await _userManager.GetUserAsync(User);
                var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                var workoutPlans = _workoutPlanService.GetWorkoutPlansForUser(user.Id);
                var achievements = _dbContext.Achievements.Where(c => c.AppUserId == userId).ToList();

                var viewModel = new DashboardVM
                {
                    UserName = user.UserName,
                    WorkoutPlans = workoutPlans,
                    Achievements = achievements,
                };

                return View(viewModel);
        }

        public IActionResult Details(int id)
        {

            var workoutPlan = _dbContext.WorkoutPlans.Include(wp => wp.Exercises).FirstOrDefault(wp => wp.WorkoutPlanId == id);

            var exercises = _dbContext.ExercisesInPlans.Where(e => e.WorkoutPlanId == workoutPlan.WorkoutPlanId).ToList();

            workoutPlan.Exercises = exercises;

            if (workoutPlan == null)
            {
                return NotFound();
            }

            var viewModel = new WorkoutPlanDetailsVM
            {
                WorkoutPlan = workoutPlan
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult CreateAchievement(string achievementName)
        {
            if (!string.IsNullOrEmpty(achievementName))
            {
                var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                var achievement = new Achievement
                {
                    Name = achievementName,
                    CompletionDate = DateTime.Now,
                    AppUserId = userId
                };

                _dbContext.Achievements.Add(achievement);
                _dbContext.SaveChanges();
            }

            return RedirectToAction("Index"); // Redirect to the dashboard or any other desired page
        }
    }
}

TrainingApp/Controllers/WorkoutPlanController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Data.Entity;
using System.Security.Claims;
using TrainingApp.Data;
using TrainingApp.Models;
using TrainingApp.Service;

namespace TrainingApp.Controllers
{
    public class WorkoutPlanController : Controller
    {
        private readonly AppDbContext _dbContext;
        private readonly UserManager<AppUser> _userManager;
        private readonly IWorkoutPlanService _workoutPlanService;

        public WorkoutPlanController(AppDbContext dbContext, UserManager<AppUser> userManager)
        {
            _dbContext = dbContext;
            _userManager = userManager;

        }

        [HttpGet]
        public IActionResult Create()
        {
            var VM = new CreateWorkoutPlanVM();
            VM.SelectedExercises = new List<string>();
            return View(VM);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateWorkoutPlanVM viewModel)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);

            if (ModelState.IsValid)
            {
                var workoutPlan = new WorkoutPlan
                {
                    Name = viewModel.Name,
                    Description = viewModel.Description,
                    DurationInDays = viewModel.DurationInDays,
                    StartDate = viewModel.StartDate,
                    AppUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value
                };

                var data = string.Concat(viewModel.SelectedExercises);

                var secondData = JsonConvert.DeserializeObject<List<ExerciseInPlan>>(data);

                foreach (var item in secondData)
                {
                    workoutPlan.Exercises.Add(new ExerciseInPlan { Name = item.Name, Sets = item.Sets, Reps = item.Reps });
                }

               await _dbContext.WorkoutPlans.AddAsync(workoutPlan);
               await _dbContext.SaveChangesAsync();

                return RedirectToAction("Details", "Dashboard",new { id = workoutPlan.WorkoutPlanId});
            }

            // If the model state is not valid, redisplay the form with errors
            return View(viewModel);
        }

        //public void CreateWorkoutPlan(WorkoutPlan workoutPlan, List<string> selectedExercises, List<int> sets, List<int> reps)
        //{
        //    List<ExerciseInPlan> exercises = CreateExercises(selectedExercises, sets, reps);

        //    // Associate the exercises with the workout plan
        //    workoutPlan.Exercises = exercises;

        //    _dbContext.WorkoutPlans.Add(workoutPlan);
        //    _dbContext.SaveChanges();
        //}
        //private List<ExerciseInPlan> CreateExercises(List<string> selectedExercises, List<int> sets, List<int> reps)
        //{
        //    List<ExerciseInPlan> exercises = new List<ExerciseInPlan>();

        //    for (int i = 0; i < selectedExercises.Count; i++)
        //    {
        //        ExerciseInPlan exercise = new ExerciseInPlan
        //        {
        //            Name = selectedExercises[i],
        //            Sets = sets[i],
        //            Reps = reps[i]
        //        };

        //        exercises.Add(exercise);
        //    }

        //    return exercises;
        //}

        [HttpPost]
        public IActionResult AddExercise([FromBody]string exercise, [FromServices] CreateWorkoutPlanVM vm)
        {
            // Use the service to add the exercise to the SelectedExercises list

            // Return a response if needed
            // vm.SelectedExercises.Add(exercise);
            vm.SelectedExercises = new List<string>();
            _workoutPlanService.AddExercise(vm, exercise);
            return Ok();
        }

        public IActionResult GetSelectedExercises([FromServices] CreateWorkoutPlanVM viewModel)
        {
            // Get the list of selected exercises from the viewModel
            var selectedExercises = _workoutPlanService.GetSelectedExercises(viewModel);

            // Return the list as JSON
            return Json(selectedExercises);
        }

        [HttpGet]
        public IActionResult ViewPlan(int id)
        {
            // Display details of a specific workout plan
            var workoutPlan = _dbContext.WorkoutPlans
                .Include(wp => wp.Exercises)
                .FirstOrDefault(wp => wp.WorkoutPlanId == id);

            if (workoutPlan == null)
            {
                return NotFound();
            }

            return View(workoutPlan);
        }
    }
}

TrainingApp/Views/Dashboard/Details.cshtml
@model TrainingApp.Models.WorkoutPlanDetailsVM

<h5>Workout plan /</h5>  <h2 class="mb-4"> @Model.WorkoutPlan.Name</h2>

@*<h3>@Model.WorkoutPlan.Name</h3>*@

<p>@*<strong>Description:</strong>*@ @Model.WorkoutPlan.Description</p>
<p><strong>Duration:</strong> @Model.WorkoutPlan.DurationInDays days</p>
<p><strong>Start Date:</strong> @Model.WorkoutPlan.StartDate.ToShortDateString()</p>
<p><strong>End Date:</strong> @Model.WorkoutPlan.EndDate.ToShortDateString()</p>


@if (Model.WorkoutPlan.Exercises.Any())
{
<h3>Exercises</h3>
    <ul>
        @foreach (var exercise in Model.WorkoutPlan.Exercises)
        {
             @Html.Raw(exercise.Sets != 0 && exercise.Reps != 0 ? $"<li>{@exercise.Name} - Sets: {@exercise.Sets}, Reps: {@exercise.Reps}</li>" : $"<li>{@exercise.Name}</li>");
        }
    </ul>
}

@*else
{
    <p>No exercises found for this workout plan.</p>
}*@

TrainingApp/Views/Dashboard/index.cshtml
@model TrainingApp.Models.DashboardVM

<div class="col-md-6">
            <h2 class="mb-4">Signed in as @Model.UserName</h2>
            @*<img src="@Model.ProfilePictureUrl" alt="Profile Picture" class="img-fluid rounded-circle mb-4" />*@
</div>
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center mb-4">Your Workout Plans</h2>

            @if (Model.WorkoutPlans.Any())
            {
                <ul class="list-group">
                    @foreach (var plan in Model.WorkoutPlans)
                    {
                        <li class="list-group-item mb-3" style="border:1px solid black">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                    <h5>@plan.Name</h5>
                                    <p class="mb-0">Start Date: @plan.StartDate.ToShortDateString() | End Date: @plan.EndDate.ToShortDateString()</p>
                                </div>
                            </div>
                                <a asp-controller="Dashboard" asp-action="Details" asp-route-id="@plan.WorkoutPlanId" class="btn btn-sm btn-primary mt-3">Details</a>
                        </li>
                    }
                </ul>
            }
                <a asp-action="Create" asp-controller="WorkoutPlan" class="btn btn-primary mt-3">Create a new workout plan</a>
     @*       else
            {
                <p class="mt-3">No workout plans found. <a asp-action="Create" asp-controller="WorkoutPlan" class="btn btn-success">Create a new workout plan</a>.</p>
            }*@
        </div>
    </div>
</div>

<div class="container mt-5">
    

    <div class="row">
        <div class="col-md-12">
            <h2 class="mb-4 text-center">Achievements</h2>
            <div>
                <ul class="list-group">
                    @foreach (var item in Model.Achievements)
                    {
          <li class="list-group-item mb-3" style="max-width:300px; border:1px solid black">
    <div>
        <h5 style="word-wrap: break-word">@item.Name</h5>
        <p class="mb-0">Date: @item.CompletionDate.ToShortDateString()</p>
    </div>
</li>
                     }
                </ul>
            </div>

            <button id="toggleForm" class="btn btn-primary mt-4">Create Achievement</button>

            <form id="achievementForm" asp-controller="Dashboard" asp-action="CreateAchievement" method="post" style="display: none;" class="mt-3">
                <div class="form-group">
                    <label for="achievementName">Describe achievement:</label>

                    <div class="input-group">

                        <textarea id="achievementName" name="achievementName" required class="form-control"></textarea>
                        
                        <div class="input-group-append ms-2">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                </div>
                </div>
            </form>
        </div>
    </div>
</div>


<script>
    document.addEventListener("DOMContentLoaded", function () {
        var form = document.getElementById("achievementForm");
        form.style.display = "none";

        var toggleButton = document.getElementById("toggleForm");

        toggleButton.addEventListener("click", function () {

            form.style.display = form.style.display === "none" ? "block" : "none";
        });
    });
</script>